### ISSUE TITLE
Setup CI testing payload executor

### ISSUE THREAD

**Issue by kgugala** [antmicro/litex-rowhammer-tester#12]
Now when the executor is ready we should have a CI system checking for the regressions. Let's use migen sim for unit testing and Verilator for system tests

**Comment by jedrzejboczar** [comment]
We're already testing Payload Executor in CI using the Migen-based test suite. Having the unit tests there is probably no need to run tests in Verilator, as the issues we find are mostly due to hardware problems and probably wouldn't be seen in Verilator-based simulations anyway. I will close this issue for now, as it is partially done, and if we decide that we need a full system test we can open a separate issue for that.
